### PR TITLE
Fix #487

### LINKED ISSUE #487: Add support for proxy configuration in .npmbuildrc
Hi
We need to set proxy in webpack.config.js that create with `lnbs-start` in each liferay js portlets.
by add this feature we can test any APIs in local liferay portlets.
for example if we add these lines in .npmbuildrc : 

```
    "port": "9090",
    "proxy": {
        "/o/v1/chimp/**": {
            "target": "http://localhost:8080"
        }
    },
```
 
all requests pass to the chimp portlet in liferay that is running on port 8080.

### PR DESCRIPTION
**Pull request by alimahsis**

### CODE REVIEW

**Comment by alimahsis** [comment]
@izaera please review this pull request.
thanks.

**Comment by izaera** [comment]
Looks good :+1: . I will merge it.

Thx :-)

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
Resent as #501 wiith minor modifications to the commit subject.

**Pull request closed without merging**
