### PR TITLE
Issue 265: Optionally support configuring a port for Webpack - without forcing a default

### PR DESCRIPTION
**Pull request by reinrl**
This relates to my comment on https://github.com/liferay/liferay-js-toolkit/issues/265

### CODE REVIEW

**Comment by izaera** [comment]
First of all thanks for the contribution :-).

I will create an issue for this so that it can be assigned to a milestone, that we use to keep track of what goes in each version. 

Then, I'll rewrite the commits to reflect the issue number and merge the patch into the `develop` branch which is the one we use for changes. Master just reflects the status of the latest released version, but we don't do any development on it.

This is just to inform you of what will happen so that you don't think I'm just closing this PR and not merging it when I start working on it.

Cheers,
Ivan

**Comment by izaera** [comment]
I have created https://github.com/liferay/liferay-js-toolkit/issues/342

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
Resent as https://github.com/liferay/liferay-js-toolkit/pull/343

Thx.

**Comment by reinrl** [comment]
> First of all thanks for the contribution :-).
> 
> I will create an issue for this so that it can be assigned to a milestone, that we use to keep track of what goes in each version.
> 
> Then, I'll rewrite the commits to reflect the issue number and merge the patch into the `develop` branch which is the one we use for changes. Master just reflects the status of the latest released version, but we don't do any development on it.
> 
> This is just to inform you of what will happen so that you don't think I'm just closing this PR and not merging it when I start working on it.
> 
> Cheers,
> Ivan

Ivan - no worries, thanks for the explanation! If there is more that I can do on my side next time to make things a little easier on you, please let me know. Otherwise, hopefully this was easy enough to follow (and thanks for the follow up on my community forum posts, that helps!).

**Comment by izaera** [comment]
@reinrl It was OK. We usually create an issue for any change and prefix commit messages with  `Fixes #nnn: ` referencing the issue. But I can do it, it's OK.

Thx :-)

**Pull request closed without merging**
